script:
  - ./checkout-externals
  - ./make-with-jit
  - make run_built_tests

before_install:
  - sudo apt-add-repository ppa:linuxjedi/ppa
  - sudo apt-get update
  - sudo apt-get install libffi-dev libuv

os:
  - osx
